"""Package export: stitch all per-asset .md into one deliverable (.md + .pdf).

Reads the rendered markdown for each asset in a fixed order, writes a combined
Product_Package.md, and renders Product_Package.pdf with ReportLab. Fonts are bundled
in assets/fonts so the PDF looks the same on any OS; falls back to Helvetica if absent.
"""
from __future__ import annotations

import re
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (HRFlowable, ListFlowable, ListItem, PageBreak,
                                Paragraph, SimpleDocTemplate, Spacer)

# asset stage -> section title, in deliverable order
SECTIONS = [
    ("product_package", "Product Package"),
    ("core_deliverables", "Core Deliverables"),
    ("bonus_deliverables", "Bonus Deliverables"),
    ("order_bump", "Order Bump"),
    ("reels", "Reels"),
    ("carousels", "Carousels"),
    ("posts", "Social Posts"),
    ("story_prompts", "Story Prompts"),
    ("cta_captions", "CTA Captions"),
    ("dm_keyword_prompts", "DM Keyword Map"),
    ("manychat", "DM Automation Flow"),
    ("dm_automation", "DM Automation"),
    ("checkout", "Checkout & Delivery Assets"),
    ("hierarchy_validation", "Hierarchy Validation Report"),
]

_INK = colors.HexColor("#1b2733")
_ACCENT = colors.HexColor("#234f4c")
_RULE = colors.HexColor("#d6dde3")
_ASSETS = Path(__file__).resolve().parent.parent / "assets" / "fonts"


def _register_fonts() -> str:
    """Register DejaVu if bundled; return the base font family name to use."""
    reg, bold, obl = (_ASSETS / "DejaVuSans.ttf", _ASSETS / "DejaVuSans-Bold.ttf",
                      _ASSETS / "DejaVuSans-Oblique.ttf")
    if reg.exists() and bold.exists():
        pdfmetrics.registerFont(TTFont("PkgSans", str(reg)))
        pdfmetrics.registerFont(TTFont("PkgSans-Bold", str(bold)))
        if obl.exists():
            pdfmetrics.registerFont(TTFont("PkgSans-Oblique", str(obl)))
        pdfmetrics.registerFontFamily("PkgSans", normal="PkgSans", bold="PkgSans-Bold",
                                      italic="PkgSans-Oblique" if obl.exists() else "PkgSans",
                                      boldItalic="PkgSans-Bold")
        return "PkgSans"
    return "Helvetica"  # built-in fallback


def build_combined_markdown(root: Path, offer_name: str) -> str:
    parts = [f"# {offer_name} — Product Package\n",
             "_Generated by the AI Product Production Factory._\n"]
    for stage, title in SECTIONS:
        md = root / f"{stage}.md"
        if md.exists():
            parts.append(f"\n\n---\n\n{md.read_text(encoding='utf-8').strip()}\n")
    return "\n".join(parts)


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _inline(text: str) -> str:
    text = _esc(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)          # **bold**
    text = re.sub(r"`([^`]+)`", r'<font face="Courier">\1</font>', text)  # `code`
    return text


def render_pdf(markdown: str, out_path: Path, family: str) -> None:
    ascii_only = family == "Helvetica"
    if ascii_only:  # scrub glyphs the built-in font lacks
        for a, b in [("•", "*"), ("→", "->"), ("↳", "->"), ("✓", "[x]"), ("✗", "[ ]"),
                     ("–", "-"), ("—", "--"), ("·", "-"), ("’", "'"), ("‘", "'"),
                     ("“", '"'), ("”", '"'), ("■", "#"), ("⚠", "!")]:
            markdown = markdown.replace(a, b)
    bold = f"{family}-Bold" if family != "Helvetica" else "Helvetica-Bold"

    def st(size, lead, **kw):
        return ParagraphStyle("s", fontName=family, fontSize=size, leading=lead, textColor=_INK, **kw)

    styles = {
        "h1": ParagraphStyle("h1", fontName=bold, fontSize=18, leading=22, textColor=_ACCENT,
                             spaceBefore=14, spaceAfter=8),
        "h2": ParagraphStyle("h2", fontName=bold, fontSize=13, leading=17, textColor=_ACCENT,
                             spaceBefore=10, spaceAfter=5),
        "h3": ParagraphStyle("h3", fontName=bold, fontSize=11, leading=15, textColor=_INK,
                             spaceBefore=6, spaceAfter=3),
        "body": st(10, 14, spaceAfter=5),
        "bullet": st(10, 13.5, spaceAfter=2),
    }

    story, bullets = [], []

    def flush_bullets():
        if bullets:
            story.append(ListFlowable(
                [ListItem(Paragraph(b, styles["bullet"]), leftIndent=10, value="•" if not ascii_only else "-")
                 for b in bullets], bulletType="bullet", leftIndent=12))
            bullets.clear()

    for line in markdown.splitlines():
        s = line.rstrip()
        if s.startswith("### "):
            flush_bullets(); story.append(Paragraph(_inline(s[4:]), styles["h3"]))
        elif s.startswith("## "):
            flush_bullets(); story.append(Paragraph(_inline(s[3:]), styles["h2"]))
        elif s.startswith("# "):
            flush_bullets(); story.append(Paragraph(_inline(s[2:]), styles["h1"]))
        elif s.strip() in ("---", "***"):
            flush_bullets(); story.append(HRFlowable(width="100%", thickness=0.6, color=_RULE,
                                                     spaceBefore=8, spaceAfter=8))
        elif s.lstrip().startswith(("- ", "* ")):
            bullets.append(_inline(s.lstrip()[2:]))
        elif not s.strip():
            flush_bullets(); story.append(Spacer(1, 4))
        else:
            flush_bullets(); story.append(Paragraph(_inline(s), styles["body"]))
    flush_bullets()

    SimpleDocTemplate(str(out_path), pagesize=LETTER, leftMargin=0.9 * inch,
                      rightMargin=0.9 * inch, topMargin=0.9 * inch, bottomMargin=0.9 * inch,
                      title="Product Package").build(story)


def package(root: Path, offer_name: str) -> tuple[Path, Path]:
    """Write Product_Package.md and Product_Package.pdf into the offer's output folder."""
    family = _register_fonts()
    md = build_combined_markdown(root, offer_name)
    md_path = root / "Product_Package.md"
    md_path.write_text(md, encoding="utf-8")
    pdf_path = root / "Product_Package.pdf"
    render_pdf(md, pdf_path, family)
    return md_path, pdf_path
